### ISSUE TITLE
Replace moment with dayjs

### ISSUE THREAD

**Issue by niftylettuce** [jamiter/simple-recur#4]
Moment is unmaintained and has several core bugs in the 2.x release.  The 3.x release is not ready or out yet, and dayjs is the alternative nearly everyone is using now.  If I submit a PR to this package to use dayjs, would you accept and major version bump for us?

**Comment by niftylettuce** [comment]
Note I also published https://github.com/niftylettuce/dayjs-with-plugins if you personally need a momentjs drop-in replacement!

**Comment by Cliffzz** [comment]
Closing issue see: https://github.com/Swydo/simple-recur/pull/5#issuecomment-681875653
